/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargosRouteImport } from './routes/cargos'
import { Route as CriteriosRouteImport } from './routes/criterios'
import { Route as EmpresasRouteImport } from './routes/empresas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargosRoute = CargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => rootRouteImport,
} as any)
const CriteriosRoute = CriteriosRouteImport.update({
  id: '/criterios',
  path: '/criterios',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cargos': typeof CargosRoute
  '/criterios': typeof CriteriosRoute
  '/empresas': typeof EmpresasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargos': typeof CargosRoute
  '/criterios': typeof CriteriosRoute
  '/empresas': typeof EmpresasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cargos': typeof CargosRoute
  '/criterios': typeof CriteriosRoute
  '/empresas': typeof EmpresasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cargos' | '/criterios' | '/empresas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cargos' | '/criterios' | '/empresas'
  id: '__root__' | '/' | '/cargos' | '/criterios' | '/empresas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargosRoute: typeof CargosRoute
  CriteriosRoute: typeof CriteriosRoute
  EmpresasRoute: typeof EmpresasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargos': {
      id: '/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof CargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criterios': {
      id: '/criterios'
      path: '/criterios'
      fullPath: '/criterios'
      preLoaderRoute: typeof CriteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargosRoute: CargosRoute,
  CriteriosRoute: CriteriosRoute,
  EmpresasRoute: EmpresasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
